Upgrade payments web to java 21 and latest spring boot version
companieshouse/payments.web.ch.gov.uk pull request #91
Opened 2024-10-07 08:38 UTC by vshastri-ch

2024-10-07 08:44 UTC, foman-ch requested changes

2024-10-07 08:44 UTC, foman-ch commented on src/main/java/uk/gov/companieshouse/web/payments/controller/PaymentSummaryController.java
>  import org.springframework.web.bind.annotation.*;
could remove the wildcard import :)

2024-10-07 08:44 UTC, foman-ch commented on src/main/resources/application.properties
> +management.endpoints.web.path-mapping.health=payments-web/healthcheck
think you might need a forward slash at the start of this as well

2024-10-07 08:44 UTC, foman-ch commented on src/test/java/uk/gov/companieshouse/web/payments/controller/PaymentSummaryControllerTests.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
wildcard import

2024-10-08 07:10 UTC, foman-ch commented on src/main/resources/application.properties
> +management.endpoints.web.path-mapping.health=payments-web/healthcheck
think you can ignore this actually, seems like some services include and some don't

2024-10-08 10:52 UTC, foman-ch approved these changes

2024-10-08 13:20 UTC, dhawes-ch approved these changes

2024-10-08 13:29 UTC, merged